# Generated by Django 3.0.2 on 2020-01-30 07:47

from django.db import migrations, models
import django.utils.timezone
import matrimony_app.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=10, verbose_name='phone number')),
                ('password', models.CharField(blank=True, max_length=120, verbose_name='password')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registered date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', matrimony_app.managers.UserManager()),
            ],
        ),
    ]
